In [1]:
import pandas as pd
import plotly.express as px

In [2]:
# Load data without a header -see original file
df = pd.read_excel("DSIDE_data_oceans_and_coasts_news_articles - Sheet1.ods", header=None)

In [3]:
df.iloc[8]

0     3 Chinese vessels escorted to EC harbour on su...
1                                            23/05/2016
2     http://ewn.co.za/2016/05/23/3-Chinese-vessels-...
3     Illegal fishing vessels spotted in the Eastern...
4     Three illegal Chinese fishing vessels escourte...
5                                   East London harbour
6                               20/05/2016 - 22/05/2016
7                                                   NaN
8                                                   NaN
9                                                   NaN
10                                                  NaN
11                                                  NaN
12                                                  NaN
13                                                  NaN
14                                                  NaN
15                                                  NaN
16                                                  NaN
17                                                  NaN
18                                                  NaN
19                                                  ewn
Name: 8, dtype: object

In [4]:
# Keep only useful columns and give them useful names
df_clean = df[[0, 1, 2, 5, 6, 19]].copy()
df_clean.columns = ["headlines", "publication_date", "url", "location", "event_date", "category"]

df_clean.head(10)

,headlines,publication_date,url,location,event_date,category
0,Unprotected and open to plunder,29/05/2016,http://www.iol.co.za/news/south-africa/kwazulu...,Eastern Cape,23/05/2016 - 29/05/2016,illegal fishing
1,R303m dedicated towards protecting parts of SA...,6/13/2016,http://traveller24.news24.com/Explore/Green/r3...,"Umgeni River Mouth, near the Blue Lagoon estua...",08/06/2016,waste
2,South Africa: Beach Clean-Up to Mark World Oce...,13/06/2016,http://allafrica.com/stories/201606131641.html,"Umgeni River Mouth, near the Blue Lagoon estua...",08/06/2016,waste
3,Spare a thought on World Oceans Day,07/06/2016,http://www.iol.co.za/capetimes/spare-a-thought...,KwaZulu-Natal South Coast and Seaforth Beach i...,08/06/2016,sea life
4,CSIR’s SeaFAR aiding authorities to protect SA...,06/2016,http://www.csir.co.za/news/2016/06/Watching%20...,South Africa,05/2015,development
5,Turning the tide on poaching: Will new policy ...,06/06/2016,http://ewn.co.za/2016/06/06/Turning-the-tide-o...,South Africa,08/03/2016,illegal fishing
6,Protecting the oceans from plastic starts inland,09/06/2016,http://www.bdlive.co.za/opinion/2016/06/09/pro...,South Africa,08/06/2016,bdlive
7,Locals fume over Chinese fishing fleets,22/05/2016,http://www.iol.co.za/news/south-africa/kwazulu...,"Eastern Cape, Cape Town Harbour",21/06/2016,iol
8,3 Chinese vessels escorted to EC harbour on su...,23/05/2016,http://ewn.co.za/2016/05/23/3-Chinese-vessels-...,East London harbour,20/05/2016 - 22/05/2016,ewn
9,CSIR technology “sees” vessels even if Automat...,03/06/2016,http://www.defenceweb.co.za/index.php?option=c...,South Africa,05/2015,illegal fishing

In [13]:
# Convert dates
df_clean['publication_date'] = pd.to_datetime(df_clean['publication_date'], dayfirst=True, errors='coerce')
df_clean['event_date'] = pd.to_datetime(df_clean['event_date'], dayfirst=True, errors='coerce')

In [14]:
df_clean.head(10)

,headlines,publication_date,url,location,event_date,category,date
0,Unprotected and open to plunder,2016-05-29,http://www.iol.co.za/news/south-africa/kwazulu...,Eastern Cape,NaT,illegal fishing,2016-05-29
1,R303m dedicated towards protecting parts of SA...,NaT,http://traveller24.news24.com/Explore/Green/r3...,"Umgeni River Mouth, near the Blue Lagoon estua...",2016-08-06,waste,2016-08-06
2,South Africa: Beach Clean-Up to Mark World Oce...,2016-06-13,http://allafrica.com/stories/201606131641.html,"Umgeni River Mouth, near the Blue Lagoon estua...",2016-08-06,waste,2016-08-06
3,Spare a thought on World Oceans Day,2016-06-07,http://www.iol.co.za/capetimes/spare-a-thought...,KwaZulu-Natal South Coast and Seaforth Beach i...,2016-08-06,sea life,2016-08-06
4,CSIR’s SeaFAR aiding authorities to protect SA...,NaT,http://www.csir.co.za/news/2016/06/Watching%20...,South Africa,2015-05-01,development,2015-05-01
5,Turning the tide on poaching: Will new policy ...,2016-06-06,http://ewn.co.za/2016/06/06/Turning-the-tide-o...,South Africa,2016-08-03,illegal fishing,2016-08-03
9,CSIR technology “sees” vessels even if Automat...,2016-06-03,http://www.defenceweb.co.za/index.php?option=c...,South Africa,2015-05-01,illegal fishing,2015-05-01
10,Navy plays major role in impounding 600 tons o...,2016-05-26,http://www.defenceweb.co.za/index.php?option=c...,East London harbour,NaT,illegal fishing,2016-05-26
11,Another three Chinese fishing trawlers escorte...,2016-05-23,http://www.defenceweb.co.za/index.php?option=c...,East London harbour,2016-05-23,illegal fishing,2016-05-23
12,SAMSA investigating seized Chinese trawler,2016-05-17,http://www.defenceweb.co.za/index.php?option=c...,South African Territorial Waters around Port E...,NaT,illegal fishing,2016-05-17

Publication or event dates couldn't be parsed for rows 0,1 , and 4. Row 6, 7, and 8 have the name of the publication instead of the category. Things aren't looking good for my already tiny dataset.

In [15]:
# How many have at least ONE valid date?
has_pub_date = df_clean['publication_date'].notna()
has_event_date = df_clean['event_date'].notna()
has_any_date = has_pub_date | has_event_date

print(f"Articles with at least one date: {has_any_date.sum()} / {len(df_clean)}")

# How many have valid categories (not publication names)?
# Let's see all unique categories
print(f"\nAll categories:\n{df_clean['category'].value_counts()}")

Articles with at least one date: 86 / 86

All categories:
category
illegal fishing    30
development        15
red tide           13
waste              11
natural event       7
sea life            6
public concern      4
Name: count, dtype: int64

In [16]:
# Fill missing event dates with publication dates
df_clean['date'] = df_clean['event_date'].fillna(df_clean['publication_date'])

In [17]:
df_clean.head(10)

,headlines,publication_date,url,location,event_date,category,date
0,Unprotected and open to plunder,2016-05-29,http://www.iol.co.za/news/south-africa/kwazulu...,Eastern Cape,NaT,illegal fishing,2016-05-29
1,R303m dedicated towards protecting parts of SA...,NaT,http://traveller24.news24.com/Explore/Green/r3...,"Umgeni River Mouth, near the Blue Lagoon estua...",2016-08-06,waste,2016-08-06
2,South Africa: Beach Clean-Up to Mark World Oce...,2016-06-13,http://allafrica.com/stories/201606131641.html,"Umgeni River Mouth, near the Blue Lagoon estua...",2016-08-06,waste,2016-08-06
3,Spare a thought on World Oceans Day,2016-06-07,http://www.iol.co.za/capetimes/spare-a-thought...,KwaZulu-Natal South Coast and Seaforth Beach i...,2016-08-06,sea life,2016-08-06
4,CSIR’s SeaFAR aiding authorities to protect SA...,NaT,http://www.csir.co.za/news/2016/06/Watching%20...,South Africa,2015-05-01,development,2015-05-01
5,Turning the tide on poaching: Will new policy ...,2016-06-06,http://ewn.co.za/2016/06/06/Turning-the-tide-o...,South Africa,2016-08-03,illegal fishing,2016-08-03
9,CSIR technology “sees” vessels even if Automat...,2016-06-03,http://www.defenceweb.co.za/index.php?option=c...,South Africa,2015-05-01,illegal fishing,2015-05-01
10,Navy plays major role in impounding 600 tons o...,2016-05-26,http://www.defenceweb.co.za/index.php?option=c...,East London harbour,NaT,illegal fishing,2016-05-26
11,Another three Chinese fishing trawlers escorte...,2016-05-23,http://www.defenceweb.co.za/index.php?option=c...,East London harbour,2016-05-23,illegal fishing,2016-05-23
12,SAMSA investigating seized Chinese trawler,2016-05-17,http://www.defenceweb.co.za/index.php?option=c...,South African Territorial Waters around Port E...,NaT,illegal fishing,2016-05-17

In [18]:
# Remove the 3 rows with publication names as categories
df_clean = df_clean[~df_clean['category'].isin(['bdlive', 'iol', 'ewn'])]

Final check that everything is fine now:

In [19]:
print(f"Clean dataset: {len(df_clean)} articles")
print(df_clean['category'].value_counts())

Clean dataset: 86 articles
category
illegal fishing    30
development        15
red tide           13
waste              11
natural event       7
sea life            6
public concern      4
Name: count, dtype: int64

86 clean articles is still good

In [12]:
# Save the clean data
#df_clean.to_csv('coastal_news_clean.csv', index=False)
#print("Data is cleaned and saved")